### ISSUE TITLE
Cherry MX keyswitches

### ISSUE THREAD

**Issue by fauxpark** [KiCad/Buttons_Switches_THT.pretty#25]
I'd like to add footprints for [Cherry MX keyswitches](http://cherryamericas.com/wp-content/uploads/2014/12/mx_cat.pdf). I think having an "official" footprint would be pretty useful for people who want to design their own mechanical keyboard or macro pad. Currently there are a few libraries [floating](https://github.com/stormbard/Keyboard.pretty) [around](https://github.com/egladman/keebs.pretty), but personally, I prefer to use as few custom/third party symbols and footprints as possible -- despite what I've heard about the current state of the libraries it seems perfectly fine for most common components.

There are a couple different variants of the switch, for example PCB mount vs. plate mount (PCB mount has two extra NPTHs on either side for stability), pads for LEDs and diodes, and extra holes for mounting stabilisers (eg. the space bar and shift keys). The number of new footprints probably calls for their own Buttons_Switches_Cherry.pretty repo.

Additionally, the mechanical keyboard community has a system for measuring the size of keys: 1u = 19.05mm pitch (sometimes 19mm, but the Cherry MX datasheet specifies the former). The alphanumeric keys for example are all 1u, and the ANSI enter key is 2.25u wide. But how would this be reflected in the footprint name? Perhaps something like:

**SW_Cherry_MX1A_{1.00|1.25|...}u_{PCB|Plate}[_{LED|Diode}]**

The LED and diode variants, being a single footprint, would need either their own schematic symbols (SW_SPST_LED exists already), markings for placement of pre-existing footprints, or would need to be split into separate footprints and overlaid.

**Comment by SchrodingersGat** [comment]
I'm happy with your suggested naming scheme, if it is the 'default' for users of these switches. How many footprints are we talking?

**Comment by fauxpark** [comment]
The key sizes are fairly standardised. A full size ANSI layout keyboard has:
1u, 1.25u, 1.5u, 1.75u, 2u (vertical and horizontal), 2.25u, 2.75u, 6.25u
Plus the [ISO enter key](https://deskthority.net/wiki/File:ISO_return_and_2u_backspace.jpg). Most other layouts consist of a subset of this range, although the space bar can (rarely) come in some [wacky sizes](https://deskthority.net/wiki/Space_bar_dimensions). A strategically placed 1u footprint and a footprint with just the stabiliser holes could fill the gap.

So, eight or nine different sizes, each with PCB and plate variants. Aside from stabiliser holes the only difference between them would be a wider courtyard for easier alignment, but I don't know if this is a legal use of it. To keep the switch and LED matrices separate in the schematic I think simply marking out where a regular LED footprint would go might be best. It's technically not part of the component, there is just a slot in the housing where you can add one.

**Comment by SchrodingersGat** [comment]
If you're keen to contribute these, then that's great. I think that it's enough to warrant a separate library directory (repo)

**Comment by fauxpark** [comment]
Sorry, my internet was out for a couple days there. That would be great, thanks. I have the 1u PCB/plate footprints almost ready.

**Comment by SchrodingersGat** [comment]
https://github.com/KiCad/Buttons_Switches_Keyboard

Our libraries are (or are gradually becoming) grouped by *function* which in this case is keyboard related switches. 

Please submit your footprints there :)
